"""Pure derived logic.

No I/O, no global state, no clock reads: "now" is always a parameter.  Zone
and schedule logic works on naive device-local wall time.  Raw inputs are
``str | None`` exactly as stored (``None`` = row absent); unknown or
unparseable values become ``None`` and nothing raises on bad wire data.
``*_compat`` functions are behaviour-compatible reimplementations of the
controller web UI's own calculations, checked against golden vectors
(input/output pairs); everything else is library policy.
"""

from __future__ import annotations

from .alarms import (
    GENERIC_ALARM_KINDS,
    MIN_ALARM_DEBOUNCE,
    VMC_ALARM_KEYS,
    AlarmTracker,
    compute_alarms,
    token_configured,
)
from .health import heartbeat_status
from .lock import lock_state
from .master import (
    LEVEL_TEMPERATURE_KEYS,
    display_temperature,
    effective_setpoint,
    master_preset,
    preset_level,
    setpoint_mismatch,
)
from .override import override_applicable, zone_override
from .parse import (
    nonempty,
    parse_availability,
    parse_device_timestamp,
    parse_fan_speed,
    parse_level,
    parse_master_mode,
    parse_master_set_point,
    parse_season,
    parse_vmc_mode,
    parse_vmc_state,
    parse_zone_setp,
)
from .presence import (
    WIDTH_ACTUATORS,
    WIDTH_FANCOILS,
    WIDTH_VMCS,
    WIDTH_ZONES,
    present_units,
    unit_id,
    unit_index,
)
from .running import program_source, running_program
from .schedule import (
    CRONO_PRESET,
    SLOT_DURATION,
    SLOTS_PER_DAY,
    js_unary_plus,
    next_slot_boundary,
    program_index_map_compat,
    program_map_compat,
    season_suffix,
    slot_of,
    slot_start,
    split_override_program,
    split_program,
    week_programs,
    weekday_js,
)
from .transitions import DEFAULT_HORIZON, next_level_change, next_transition_compat
from .types import (
    AlarmCondition,
    AlarmInputs,
    AlarmView,
    FanState,
    ForecastItem,
    FreeCoolingState,
    GenericAlarmRow,
    HeartbeatStatus,
    LockInfo,
    NextTransitionCompat,
    OverrideRow,
    OverrideState,
    Program,
    ScheduleRow,
    TrackedAlarm,
    UnitPresence,
    VmcOperation,
    WeatherDayInfo,
    WeatherInfo,
    WeekPrograms,
    ZoneEffective,
    ZoneInputs,
)
from .vmc import (
    VMC_MODE_AVAILABILITY_KEYS,
    mode_availability,
    selectable_modes,
    vmc_fan,
    vmc_free_cooling,
    vmc_operation,
)
from .weather import parse_forecast, parse_weather
from .zone import (
    HUMIDITY_NO_SENSOR,
    zone_effective,
    zone_humidity,
    zone_hvac_action,
    zone_level_at,
    zone_mode_preset_source,
)

__all__ = [
    "CRONO_PRESET",
    "DEFAULT_HORIZON",
    "GENERIC_ALARM_KINDS",
    "HUMIDITY_NO_SENSOR",
    "LEVEL_TEMPERATURE_KEYS",
    "MIN_ALARM_DEBOUNCE",
    "SLOTS_PER_DAY",
    "SLOT_DURATION",
    "VMC_ALARM_KEYS",
    "VMC_MODE_AVAILABILITY_KEYS",
    "WIDTH_ACTUATORS",
    "WIDTH_FANCOILS",
    "WIDTH_VMCS",
    "WIDTH_ZONES",
    "AlarmCondition",
    "AlarmInputs",
    "AlarmTracker",
    "AlarmView",
    "FanState",
    "ForecastItem",
    "FreeCoolingState",
    "GenericAlarmRow",
    "HeartbeatStatus",
    "LockInfo",
    "NextTransitionCompat",
    "OverrideRow",
    "OverrideState",
    "Program",
    "ScheduleRow",
    "TrackedAlarm",
    "UnitPresence",
    "VmcOperation",
    "WeatherDayInfo",
    "WeatherInfo",
    "WeekPrograms",
    "ZoneEffective",
    "ZoneInputs",
    "compute_alarms",
    "display_temperature",
    "effective_setpoint",
    "heartbeat_status",
    "js_unary_plus",
    "lock_state",
    "master_preset",
    "mode_availability",
    "next_level_change",
    "next_slot_boundary",
    "next_transition_compat",
    "nonempty",
    "override_applicable",
    "parse_availability",
    "parse_device_timestamp",
    "parse_fan_speed",
    "parse_forecast",
    "parse_level",
    "parse_master_mode",
    "parse_master_set_point",
    "parse_season",
    "parse_vmc_mode",
    "parse_vmc_state",
    "parse_weather",
    "parse_zone_setp",
    "present_units",
    "preset_level",
    "program_index_map_compat",
    "program_map_compat",
    "program_source",
    "running_program",
    "season_suffix",
    "selectable_modes",
    "setpoint_mismatch",
    "slot_of",
    "slot_start",
    "split_override_program",
    "split_program",
    "token_configured",
    "unit_id",
    "unit_index",
    "vmc_fan",
    "vmc_free_cooling",
    "vmc_operation",
    "week_programs",
    "weekday_js",
    "zone_effective",
    "zone_humidity",
    "zone_hvac_action",
    "zone_level_at",
    "zone_mode_preset_source",
    "zone_override",
]
