"""Loading of the golden vectors generated by ``tools/golden/generate.mjs``.

The vectors are the outputs of the vendor web-UI JS for seeded inputs.  No
vendor code is stored here (see ``tools/golden/README.md``).
"""

from __future__ import annotations

import json
import os
from collections.abc import Callable, Iterable
from functools import cache
from pathlib import Path
from typing import Any

from aiorehom.logic import ScheduleRow

GOLDEN_DIR = Path(__file__).parent
VECTOR_FILES = (
    "running_program.json",
    "program_map.json",
    "next_transition.json",
    "next_transition_dangling.json",
    "constants.json",
)
#: Report at most this many mismatching cases per test.
MAX_REPORTED = 10


@cache
def load(name: str) -> dict[str, Any]:
    """The parsed vector file ``name``."""
    data: dict[str, Any] = json.loads((GOLDEN_DIR / name).read_text(encoding="utf-8"))
    return data


def cases(name: str) -> list[dict[str, Any]]:
    """The cases of vector file ``name``."""
    items: list[dict[str, Any]] = load(name)["cases"]
    return items


def schedule_rows(rows: Iterable[list[str]]) -> tuple[ScheduleRow, ...]:
    """``[SubUni, Key, Valore]`` triples -> :class:`ScheduleRow`, in order."""
    return tuple(ScheduleRow(subuni=s, key=k, value=v) for s, k, v in rows)


def mismatches(
    items: Iterable[dict[str, Any]], check: Callable[[dict[str, Any]], object | None]
) -> list[str]:
    """Run ``check`` on every case; collect ``"#i: <detail>"`` for each non-``None`` result."""
    out: list[str] = []
    for index, case in enumerate(items):
        detail = check(case)
        if detail is not None:
            out.append(f"#{index}: {detail}")
    return out


def report(failures: list[str]) -> str:
    """A bounded failure message."""
    shown = "\n".join(failures[:MAX_REPORTED])
    return f"{len(failures)} golden case(s) differ from the vendor JS:\n{shown}"


def webui_src() -> Path | None:
    """The vendor web-UI source tree named by ``$REHOM_WEBUI_SRC``, or ``None``.

    The vendor source is not part of this repository; without the variable
    the checks that need it are skipped.
    """
    env = os.environ.get("REHOM_WEBUI_SRC")
    if not env:
        return None
    path = Path(env)
    return path if path.is_dir() else None
